server/src/main/java/seb/project/Codetech/question/entity/Answer.java, server/src/main/java/seb/project/Codetech/question/entity/question.java
질문 도메인의 Question, Answer 엔티티 작성하였습니다.
변수명이나 누락된 부분 확인 부탁드립니다!
=> feat: Answer 엔티티 작성

server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java
스낵리뷰 엔티티를 작성했습니다.
변수명이나 누락된 부분 확인 부탁드립니다!
=> feat: SnackReview 엔티티 작성

server/src/main/java/seb/project/Codetech/jpa/converter/ScoreJsonConverter.java, server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java
리뷰 점수 데이터를 Json으로 관리하는 Score 클래스 추가하였고 평점순 조회를 위한 grade 칼럼 추가하였습니다.
Score 클래스는 JSON 문자열로 파싱되어 db에 VARCHAR로 저장됩니다.
변수명이나 누락된 부분 확인해주시고 이상없으면 머지 후 로컬 db에 반영 부탁드립니다!
=> Feat/seongho/score #34

client/src/components/Header/Header.tsx, client/src/components/Header/SearchBar.tsx
=> [Feat] header navigate 적용

server/src/main/java/seb/project/Codetech/snackreview/controller/SnackReviewController.java, server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewPatchDto.java, server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewPostDto.java, server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java, server/src/main/java/seb/project/Codetech/snackreview/validation/annotation/ValidScore.java, server/src/main/java/seb/project/Codetech/snackreview/validation/validator/ScoreValidator.java, server/src/test/java/seb/project/Codetech/snackreview/entity/SnackReviewTest.java
=> [feat] SnackReviewController 초안 작성

server/src/main/java/seb/project/Codetech/global/converter/ScoreJsonConverter.java, server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java
global/converter 패키지로 컨버터 위치 통일하고 jpa/converter 패키지 제거
=> refactor: ScoreJsonConverter global/converter 패키지로 이동 (#53)

server/src/main/java/seb/project/Codetech/discount/entity/Discount.java, server/src/main/java/seb/project/Codetech/discount/entity/DiscountComment.java, server/src/main/java/seb/project/Codetech/question/entity/Answer.java, server/src/main/java/seb/project/Codetech/question/entity/Question.java, server/src/main/java/seb/project/Codetech/recommend/entity/Recommend.java, server/src/main/java/seb/project/Codetech/review/entity/Review.java, server/src/main/java/seb/project/Codetech/review/entity/ReviewComment.java, server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java, server/src/main/java/seb/project/Codetech/user/entity/User.java
=> fix: 연관관계 메소드 수정

client/data/data.json, client/package-lock.json, client/package.json, client/src/App.tsx, client/src/components/Details/ReviewDetail.tsx, client/src/components/Details/RvDetail.tsx, client/src/components/List/BestReviewList.tsx, client/src/components/List/ProductList.tsx, client/src/components/List/ReviewList.tsx, client/src/components/Selectors/MainCategory.tsx, client/src/components/ToastUI/TextViewer.tsx, client/src/pages/Main.tsx, client/src/pages/ReviewDetail.tsx, client/src/types/mainPageTypes.tsx, client/tailwind.config.js
Main Page 에서 카테고리 부분 기능 구현했습니다
프로토타입에 맞게 css 구현했습니다.
=> feat: MainPage 카테고리 기능구현

server/src/main/java/seb/project/Codetech/global/converter/ScoreJsonConverter.java, server/src/main/java/seb/project/Codetech/snackreview/controller/SnackReviewController.java, server/src/main/java/seb/project/Codetech/snackreview/controller/SnackReviewControllerV1.java, server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewControllerDto.java, server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewResponseDto.java, server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewServiceDto.java, server/src/main/java/seb/project/Codetech/snackreview/entity/Score.java, server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java, server/src/main/java/seb/project/Codetech/snackreview/mapper/SnackReviewServiceMapper.java, server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepository.java, server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepositoryImpl.java, server/src/main/java/seb/project/Codetech/snackreview/repository/SnackReviewRepository.java, server/src/main/java/seb/project/Codetech/snackreview/service/SnackReviewService.java, server/src/main/java/seb/project/Codetech/snackreview/validation/validator/ScoreValidator.java
=> feat: 스낵리뷰 조회 쿼리 구현

server/src/main/java/seb/project/Codetech/global/config/SecurityConfiguration.java, server/src/main/java/seb/project/Codetech/global/exception/ExceptionCode.java, server/src/main/java/seb/project/Codetech/question/controller/AnswerController.java, server/src/main/java/seb/project/Codetech/question/controller/QuestionController.java, server/src/main/java/seb/project/Codetech/question/dto/AnswerRequestDto.java, server/src/main/java/seb/project/Codetech/question/dto/AnswerServiceDto.java, server/src/main/java/seb/project/Codetech/question/entity/Answer.java, server/src/main/java/seb/project/Codetech/question/entity/Question.java, server/src/main/java/seb/project/Codetech/question/mapper/AnswerControllerMapper.java, server/src/main/java/seb/project/Codetech/question/mapper/AnswerServiceMapper.java, server/src/main/java/seb/project/Codetech/question/respository/AnswerRepository.java, server/src/main/java/seb/project/Codetech/question/respository/CustomQuestionRepository.java, server/src/main/java/seb/project/Codetech/question/respository/CustomQuestionRepositoryImpl.java, server/src/main/java/seb/project/Codetech/question/respository/QuestionRepository.java, server/src/main/java/seb/project/Codetech/question/service/AnswerService.java, server/src/main/java/seb/project/Codetech/question/service/QuestionService.java, server/src/main/java/seb/project/Codetech/snackreview/controller/SnackReviewController.java, server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewRequestDto.java, server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewResponseDto.java, server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java, server/src/main/java/seb/project/Codetech/snackreview/mapper/SnackReviewControllerMapper.java, server/src/main/java/seb/project/Codetech/snackreview/mapper/SnackReviewServiceMapper.java, server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepository.java, server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepositoryImpl.java, server/src/main/java/seb/project/Codetech/snackreview/service/SnackReviewService.java, server/src/main/java/seb/project/Codetech/user/entity/User.java
=> feat: Question 도메인 CUD 구현

server/src/main/java/seb/project/Codetech/global/exception/ExceptionCode.java, server/src/main/java/seb/project/Codetech/question/controller/AnswerController.java, server/src/main/java/seb/project/Codetech/question/controller/QuestionController.java, server/src/main/java/seb/project/Codetech/question/dto/QuestionRequestDto.java, server/src/main/java/seb/project/Codetech/question/dto/QuestionResponseDto.java, server/src/main/java/seb/project/Codetech/question/entity/Answer.java, server/src/main/java/seb/project/Codetech/question/entity/Question.java, server/src/main/java/seb/project/Codetech/question/respository/CustomQuestionRepository.java, server/src/main/java/seb/project/Codetech/question/respository/CustomQuestionRepositoryImpl.java, server/src/main/java/seb/project/Codetech/question/service/AnswerService.java, server/src/main/java/seb/project/Codetech/question/service/QuestionService.java, server/src/main/java/seb/project/Codetech/snackreview/controller/SnackReviewController.java, server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewResponseDto.java, server/src/main/java/seb/project/Codetech/snackreview/entity/SnackReview.java, server/src/main/java/seb/project/Codetech/snackreview/mapper/SnackReviewServiceMapper.java, server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepository.java, server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepositoryImpl.java, server/src/main/java/seb/project/Codetech/snackreview/service/SnackReviewService.java
=> feat: 질문 채택, 질문 조회 API 구현 

client/package.json, client/src/App.css, client/src/App.tsx, client/src/components/Modal/EditPassword.tsx, client/src/components/Modal/EditProfile.tsx, client/src/components/Modal/EditProfileImg.tsx, client/src/components/Modal/OptOut.tsx, client/src/components/MyPage/MypageTab.tsx, client/src/components/MyPage/Profile.tsx, client/src/components/QuestionList/QuestionInput.tsx, client/src/components/Review/CreatSnackReview.tsx, client/src/components/Review/SnackReview.tsx, client/src/components/Review/StarRating.tsx, client/src/pages/MyPage.tsx, client/src/pages/ReviewLists.tsx, client/src/util/ServerApiCollection.tsx
=> feat: 리뷰리스트 별점기능 구현

client/src/App.tsx, client/src/components/Modal/EditProfileImg.tsx, client/src/components/Modal/OptOut.tsx, client/src/components/MyPage/Profile.tsx, client/src/components/Review/CreatSnackReview.tsx, client/src/components/Review/SnackReview.tsx, client/src/pages/Login.tsx, client/src/pages/ReviewLists.tsx, client/src/store/login.tsx, client/src/util/apiCollection.tsx
=> feat: 마이페이지 프로필 API 연동

client/src/components/Modal/OptOut.tsx, client/src/components/MyPage/Profile.tsx, client/src/util/apiCollection.tsx
=> fix: token과 관련된 여러문제를 해결했습니다

client/src/components/Modal/EditProfile.tsx, client/src/components/Modal/EditProfileImg.tsx, client/src/components/MyPage/Profile.tsx, client/src/util/apiCollection.tsx
=> faet: 마이페이지 프로필 이미지 수정 구현

server/src/main/java/seb/project/Codetech/question/dto/QuestionResponseDto.java, server/src/main/java/seb/project/Codetech/question/respository/CustomQuestionRepositoryImpl.java, server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewResponseDto.java, server/src/main/java/seb/project/Codetech/snackreview/repository/CustomSnackReviewRepositoryImpl.java
=> feat: 작성글에 작성자 식별자 추가

client/src/components/Review/SnackReview.tsx
콘솔로그에 undefined 배열 애러가 있어 수정하여 다시 머지합니다
=> Fix: console 에러 처리

client/src/components/Modal/EditProfileImg.tsx, client/src/components/MyPage/AnswersTab.tsx, client/src/components/MyPage/LikeReviewTab.tsx, client/src/components/MyPage/MypageTab.tsx, client/src/components/MyPage/QuestionsTab.tsx, client/src/components/MyPage/ReviewTabPagenation.tsx, client/src/components/MyPage/ReviewsTab.tsx, client/src/components/MyPage/SnackReviewTab.tsx, client/src/components/Selectors/ProductSelector.tsx, client/src/pages/ReviewLists.tsx, client/src/util/apiCollection.tsx
- 마이페이지 리뷰조회 탭 API 연동
- 마이페이지 리뷰탭 페이지네이션 구현
=> feat: 마이페이지 리뷰조회 탭 API 연동

server/src/main/java/seb/project/Codetech/product/service/ProductService.java, server/src/main/java/seb/project/Codetech/productstat/controller/ProductStatController.java, server/src/main/java/seb/project/Codetech/productstat/dto/ProductStatResponseDto.java, server/src/main/java/seb/project/Codetech/question/service/AnswerService.java, server/src/main/java/seb/project/Codetech/redis/config/RedisConfig.java, server/src/main/java/seb/project/Codetech/snackreview/dto/SnackReviewRequestDto.java, server/src/main/java/seb/project/Codetech/snackreview/validation/validator/ScoreValidator.java
=> fix: 스낵리뷰 유효성 검사 문제 해결

server/src/main/java/seb/project/Codetech/question/respository/CustomQuestionRepositoryImpl.java
=> fix: 질문, 답변 응답에서 유저 프로필 이미지 누락된 것 추가 (#186)

client/src/components/Modal/Confirm.tsx, client/src/components/Modal/WriteAnswer.tsx, client/src/components/QuestionList/QuestionInput.tsx, client/src/pages/Login.tsx, client/src/pages/Signup.tsx, client/src/types/mainPageTypes.tsx
- question page: 빈공란 질문 모달띄우기
- question page: 빈공란 답변 경고띄우기
- login page: email, password 공란 모달띄우기
- signup page: nickname, email, password, passwordCheck 공란 모달띄우기
=> feat: 내용이 없는 입력에 대해서 피드백을 추가했습니다.

client/src/components/Details/RvDetail.tsx, client/src/components/Header/Header.tsx, client/src/components/List/BestReviewList.tsx, client/src/components/List/ProductList.tsx, client/src/components/List/QuestionList.tsx, client/src/components/Review/CreateSnackReview.tsx, client/src/components/Review/EditSnackReview.tsx, client/src/components/Review/SnackReview.tsx, client/src/components/Selectors/MainCategory.tsx, client/src/icons/index.tsx, client/src/pages/ReviewLists.tsx, client/src/types/mainPageTypes.tsx, client/src/util/apiCollection.tsx
refresh token 사용하여 로그인 상태유지 구현
=> feat: refresh token 사용하여 로그인 상태유지 구현

client/src/components/Avatar/Avatar.tsx, client/src/components/QuestionList/Answer.tsx, client/src/components/QuestionList/AnswerMore.tsx, client/src/components/QuestionList/BodyTop.tsx, client/src/components/QuestionList/Completes.tsx, client/src/components/QuestionList/PendingAnswer.tsx, client/src/components/QuestionList/PendingQuestion.tsx, client/src/components/QuestionList/Question.tsx, client/src/components/QuestionList/QuestionInput.tsx, client/src/components/SelectBox/SelectBox.tsx, client/src/pages/QuestionLists.tsx, client/src/pages/Signup.tsx, client/src/types/mainPageTypes.tsx
1. selector 버튼 밖에 클릭하면 없애기
2. img가 null 인 친구는 저장된 이미지 보여주기
3. 회원가입할때 랜덤 img 경로 지정하기
4. 댓글이 달리면 수정이 안되게
5. 임시방편으로 댓글이 달리면 삭제도 안되게
=> Feat: 질문 page 기능추가 및 기타

client/src/components/Modal/Confirm.tsx, client/src/components/QuestionList/BodyTop.tsx, client/src/components/QuestionList/Completes.tsx, client/src/pages/QuestionLists.tsx, client/src/util/apiCollection.tsx
기존의 댓글이 달린 질문의 수정과 삭제 버튼을 감추었던 것에서
보여주되 클릭시 작동하지 않는다는 안내모달을 띄웠습니다.
- 댓글이 달린 질문의 수정과 삭제 기능 수정
=> Feat: 질문 page UX 개선

client/src/components/Modal/EditQuestion.tsx, client/src/components/QuestionList/BodyTop.tsx, client/src/pages/Signup.tsx, client/src/util/apiCollection.tsx, client/src/util/loginRefresh.tsx
util 폴더에 있는 loginRefresh.tsx의 loginRefresh 함수를 사용하여 access 토큰을 재발급 받고 해당 함수를 재시작하면 됩니다.
=> feat: refresh 토큰을 사용한 재인증 과정 간소화

client/src/components/List/BestReviewList.tsx, client/src/components/List/QuestionList.tsx, client/src/pages/Login.tsx
=> style: main page 하단에 질문부분 레이아웃 수정

client/src/components/List/BestReviewList.tsx, client/src/components/List/ProductList.tsx, client/src/components/List/QuestionList.tsx, client/src/components/Selectors/MainCategory.tsx, client/src/pages/Login.tsx
페이지 완성도를 높이기 위한 아래의 작업을 수행하였습니다.
- 레이아웃이 틀어지는 이슈를 수정
=> style: main page 반응형 레이아웃 모바일 환경 보완

client/src/components/Details/Comment.tsx, client/src/components/Details/CommentInput.tsx, client/src/components/Details/EditReviewDetail.tsx, client/src/components/Details/Like.tsx, client/src/components/Details/RvDetail.tsx, client/src/components/Header/SearchBar.tsx, client/src/components/ToastUI/TextEditor.tsx, client/src/types/mainPageTypes.tsx, client/src/util/apiCollection.tsx
좋아요 버튼 반응 => 구현을 위해 백엔드 분들에게 응답객체 추가 요청
빈 댓글 달림 => 해결
댓글 창 마진 => 해결
본인 글에서 좋아요 버튼 안보이게 구현 => 해결
댓글 이벤트시 scrollTo Top 추가
리뷰 수정 에러 => thumbnail 누락으로 인한 에러 수정
=> Feat: QA 피드백 반영

client/src/pages/Signup.tsx
=> fix: 회원가입 탈퇴한 회원 에러 핸들링 #295

client/src/components/Modal/Confirm.tsx, client/src/pages/Signup.tsx
=> fix: 회원가입 한글닉네임 에러 해결 #303

client/package-lock.json, client/src/components/Selectors/ProductSelector.tsx, client/src/components/ToastUI/TextEditor.tsx
=> fix: 리뷰작성 소분류값,모달창 수정 #308

server/src/main/java/seb/project/Codetech/review/entity/Review.java, server/src/main/java/seb/project/Codetech/review/entity/ReviewComment.java, server/src/main/java/seb/project/Codetech/review/repository/ReviewCommRepository.java, server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
=> feat: feat: 상세 리뷰 관련 서비스 로직 문제 수정 

client/src/App.tsx
웹사이트의 완성도를 높이기 위해 아래와 같은 작업을 하였습니다.
- 회원가입 이메일 인증버튼 색상 변경
- 레이아웃에 메인 div 제거 및 root 배경색 추가
- 리뷰 리스트 페이지 전반적인 기능 재배치 및 스타일 변경
=> Style/kwngmin/review list css #317

README.md, client/src/components/Details/RvDetail.tsx, client/src/components/Review/CreateSnackReview.tsx, client/src/pages/ReviewLists.tsx, server/src/main/java/seb/project/Codetech/review/entity/Review.java, server/src/main/java/seb/project/Codetech/review/entity/ReviewComment.java, server/src/main/java/seb/project/Codetech/review/repository/ReviewCommRepository.java, server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
웹사이트의 완성도를 높이기 위해 아래와 같은 작업을 하였습니다.
- 회원가입 이메일 인증버튼 색상 변경
- 레이아웃에 메인 div 제거 및 root 배경색 추가
- 리뷰 리스트 페이지 전반적인 기능 재배치 및 스타일 변경
=> [FE] review list page css 외 기타

client/src/App.css, client/src/App.tsx, client/src/components/Footer/Footer.tsx, client/src/components/Footer/Member.tsx, client/src/components/List/QuestionList.tsx, client/src/components/Review/AvgRating.tsx, client/src/components/Review/DetailReview.tsx, client/src/components/Review/SnackReview.tsx, client/src/layout/Layout.tsx, client/src/pages/ReviewLists.tsx, server/src/main/java/seb/project/Codetech/review/entity/Review.java, server/src/main/java/seb/project/Codetech/review/entity/ReviewComment.java, server/src/main/java/seb/project/Codetech/review/repository/ReviewCommRepository.java, server/src/main/java/seb/project/Codetech/review/service/ReviewService.java
웹사이트의 완성도를 높이기 위해 아래와 같은 작업을 하였습니다.
- 레이아웃에 메인 div 제거 및 root 배경색 추가
- 리뷰 리스트 페이지 전반적인 기능 재배치 및 스타일 변경
=> Style/kwngmin/review list and etc #317

server/src/main/java/seb/project/Codetech/security/config/SecurityConfig.java, server/src/main/java/seb/project/Codetech/security/oauth2/handler/OAuth2UserSuccessHandler.java, server/src/main/java/seb/project/Codetech/security/oauth2/provider/CustomOAuth2Provider.java, server/src/main/resources/application-dev.yml
* fix: 시큐리티 오류 수정 (#66)
* Merge pull request #93
* build: build.gradle 버전 관리 및 ddl-auto 변경
* feat: Audit 추상 클래스 구현 (#11)
* feat: @EnableJpaAuditing 추가 (#11)
* Merge pull request #16 from codestates-seb/feat/be-11-auditing
* feat: Question 엔티티 작성
* feat: Answer 엔티티 작성
* Merge pull request #18 from codestates-seb/feat/be-8-question
* feat: Answer 엔티티 작성
* Merge pull request #19 from codestates-seb/feat/be-8-question
* feat: User Discount DiscountComment 클래스 구현 (#10)
* Merge pull request #17 from codestates-seb/feat/be-10-user
* fix: Question 엔티티의 오타 수정
* feat: SnackReview 엔티티 작성
* Merge pull request #20 from codestates-seb/feat/be-9-snackreview
* feat: Product.java, Type.java 클래스 생성 및 구현 (#13)
* Merge pull request #21 from codestates-seb/feat/be-13-product
* feat: Recommend.java 클래스 생성 및 구현 …
=> Feat: kakao login #174 (#336)

client/src/components/Modal/AddProduct.tsx, client/src/components/Modal/ThumbnailModal.tsx, client/src/components/Selectors/CategorySelector.tsx, client/src/components/Selectors/ProductSelector.tsx, client/src/components/ToastUI/TextEditor.tsx, client/src/components/common.css, client/src/pages/WriteReview.tsx
=> fix: 리뷰작성페이지 반응형

client/src/pages/Signup.tsx
회원가입 버튼 클릭시 이메일 인증을 하지 않았으면 뜨는 팝업창 추가 #356
=> fix: 회원가입 이메일인증 팝업추가 #356

client/src/components/QuestionList/Answer.tsx, client/src/components/QuestionList/Completes.tsx, client/src/components/QuestionList/PendingQuestion.tsx, client/src/components/QuestionList/Question.tsx, client/src/components/Review/DetailReview.tsx, client/src/pages/QuestionLists.tsx
image가 테스트용 이미지로 고정되어 있는 것과
반응형 작업을 수행했습니다.
=> style: review list css 상세리뷰 image

client/src/components/Details/Comment.tsx, client/src/components/Details/CommentInput.tsx, client/src/components/Details/EditReviewDetail.tsx, client/src/components/Details/Like.tsx, client/src/components/Details/RvDetail.tsx, client/src/components/Details/SubComment.tsx, client/src/components/Footer/Footer.tsx, client/src/components/Footer/Member.tsx, client/src/icons/index.tsx
review detail page와 footer의 css를 변경하였습니다.
=> style: reviewDetail 및 footer

client/src/components/MyPage/Profile.tsx, client/src/pages/Signup.tsx
- 마이페이지에서 null 값인 이미지 처리
- 회원가입 페이지 css 수정
=> feat&style: 마이페이지  및 회원가입 

client/src/components/Header/Header.tsx, client/src/components/Modal/AddProduct.tsx, client/src/components/Modal/Confirm.tsx, client/src/components/Modal/ThumbnailModal.tsx, client/src/components/Selectors/CategorySelector.tsx, client/src/components/Selectors/ProductSelector.tsx, client/src/components/ToastUI/TextEditor.tsx, client/src/pages/WriteReview.tsx, client/src/store/darkMode.tsx, client/tailwind.config.js
=> style: 리뷰작성,제품추가,썸네일 다크모드 적용 #367

client/src/pages/Login.tsx, client/src/pages/Signup.tsx
=> style: 로그인, 로그아웃 다크모드 수정 #367

client/src/components/ToastUI/TextEditor.tsx
=> style: 토스트 에디터 다크모드 수정 #367

client/src/components/Details/Comment.tsx, client/src/components/Details/EditComment.tsx, client/src/components/Details/RvDetail.tsx, client/src/components/Details/SubComment.tsx, client/src/components/Footer/Member.tsx, client/src/components/Header/Header.tsx, client/src/components/Header/SearchBar.tsx, client/src/components/List/BestReviewList.tsx, client/src/components/Modal/OptOut.tsx, client/src/components/Modal/WriteAnswer.tsx, client/src/components/MyPage/AnswersMore.tsx, client/src/components/MyPage/AnswersTab.tsx, client/src/components/MyPage/Profile.tsx, client/src/components/QuestionList/Answer.tsx, client/src/components/QuestionList/AnswerMore.tsx, client/src/components/QuestionList/BodyTop.tsx, client/src/components/QuestionList/PendingQuestion.tsx, client/src/components/QuestionList/Question.tsx, client/src/pages/MyPage.tsx, client/src/util/apiCollection.tsx, client/src/util/loginRefresh.tsx
- 모바일: 검색 아이콘 패딩 값 조정
- 검색창하고 검색 아이콘 뜨는 가로폭 정정
- 마이페이지 내 답글의 답글더보기 버튼형식 예전 스타일로 변경
- 제품 상세에서 댓글 더보기하면 변경 안된 부분 수정
- 메인의 베스트리뷰에서 자세히보기 부분 hover 빠진거 수정
- 제품 상세에서 다크모드일때 뒤로가기버튼 hover 빠진거 수정
- 콘솔로그 모두 걷어내기
- 질문리스트에서 답변더보기 버튼 가로폭 들쑥날쑥한거 수정
=> style: 다양한 페이지와 콘포넌트의 스타일 보완 및 수정

client/src/components/Details/RvDetail.tsx, client/src/components/Modal/AddProduct.tsx, client/src/components/Modal/ThumbnailModal.tsx, client/src/components/Selectors/CategorySelector.tsx, client/src/pages/WriteReview.tsx
Reverts codestates-seb/seb40_main_011#423
=> Revert "refactor: 리뷰 작성 #422"
